import { db } from "../index.js";
import { NewUser, users } from "../schema.js";

export async function createUser(user: NewUser) {
  // .returning() makes it give us back the user we just created (with the ID generated by the DB)
  const [result] = await db.insert(users).values(user).returning();
  return result;
}
