import { db } from "../index.js";
import { NewUser, users } from "../schema.js";
import { eq } from "drizzle-orm";

export async function createUser(user: NewUser) {
  // .returning() makes it give us back the user we just created (with the ID generated by the DB)
  const [result] = await db.insert(users).values(user).returning();
  return result;
}

export async function deleteAllUsers() {
  await db.delete(users);
}

export async function getUserByEmail(email: string) {
  // return an array, so we pick the first one later
  return await db.select().from(users).where(eq(users.email, email));
}

export async function updateUser(
  id: string,
  email: string,
  hashedPassword: string,
) {
  const [updatedUser] = await db
    .update(users)
    .set({ email, hashedPassword })
    .where(eq(users.id, id))
    .returning();
  return updatedUser;
}
